name: 'test actions'
description: 'test action description'

inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  
  steps:
    - name: whatever...
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: whatever
    - name:
      run: echo "bla bla bla"
      shell: ${{ format('{0}', outputs.whatever.SELECTED_COLOR) }}

