name: 'Issue'
description: 'Composite example'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '2.6.0'
runs:
  using: "composite"
  steps:
    - name: Setup rbenv
      run: |
        exit 1
      shell: bash
      continue-on-error: true

    - name: Setup Ruby
      run: |
        exit 1
      shell: bash

