runs:
  using: "composite"
  defaults:
    run:
      #shell: bash
      working-directory: custom
  steps:
    - run: pwd
    - run: ./shell.sh
    - run: echo "bla bla 1"
    - run: echo "bla bla 2"
    - run: echo "bla bla 3"
