  using: "composite"
  steps:
    - run: printenv
      shell: bash
    - run: |
        echo ${{github.action_path}}
        echo ${{github.event_path}}
        echo ${{github.workspace}}
      shell: bash
