  
name: 'test actions'
description: 'test action description'

runs:
  using: "composite"
  steps:
  - run: printenv
    shell: bash
  - name: "run"
    env:
      WORKSPACE: echo ${{ github.workspace }}
    run: |
      echo $WORKSPACE
      echo ${{github.action_path}}
      echo ${{github.event_path}}
      echo ${{github.workspace}}
    shell: bash
