runs:
  using: "composite"
  steps:
  - name: Run failing
    run: echo $0
    shell: sh
  
  
#   using: "composite"
#   steps:
#   - run: printenv
#     shell: bash
#   - shell: bash
#     run: |
#       echo ${{github.action_path}}
#       echo ${{github.event_path}}
#       echo ${{github.workspace}}
        
#   using: "composite"
#   defaults:
#     run:
#       shell: sh
#       working-directory: ./custom
#   steps:
#     - uses: actions/checkout@v2
#     - run: echo $0
#     - run: ls

