name: 'test actions'
description: 'test action description'

inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  steps:
    - name:
      run: echo "bla bla bla"
      shell: ${{ toJSON(github) + toJSON(inputs.shell) + toJSON(strategy) + toJSON(matrix) + toJSON(steps) + toJSON(runner) + toJSON(env) + hashFiles(./*) }}

