name: 'test actions'
description: 'test action description'

inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  steps:
    - name: whatever...
      run: echo 'yellow'
    - name:
      run: echo "bla bla bla"
      shell: ${{ format('{0}, {1}', toJSON(env) , hashFiles('./*')) }}

