name: 'test actions'
description: 'test action description'

inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
runs:
  using: "composite"
  
  steps:
    - name: 'test'
      id: whatever
      run: echo "::set-output name=test::/bin/sh"
    - name:
      run: echo "bla bla bla"
      shell: ${{ format('{0}', toJSON(steps.whatever.outputs.test)) }}

