name: 'github.action_status should be lowercase'

runs:
  using: 'composite'
  steps:
  - name: Echo the action_status
    run: echo ${{ github.action_status }}
    shell: sh
  - name: Fail here
    run: exit 1
    shell: sh
  - name: Echo the action_status
    if: failure()
    run: echo ${{ github.action_status }}
    shell: sh
  - name: Check for the action_status with expression
    if: failure() && github.action_status == 'failure'
    run: echo ${{ github.action_status }} && echo 'Echoing from failure() && action_status == failure'
  - name: Check for the action_status with expression
    if: failure() && github.action_status == 'Failure'
    run: echo ${{ github.action_status }} && echo 'Echoing from failure() && action_status == Failure'
    shell: sh

 
