name: 'Issue'
description: 'Composite example'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '2.6.0'
runs:
  using: "composite"
  steps:
    - name: Setup rbenv
      run: |
        echo "::group::Installing rbenv..."
        echo "testing this"
        echo "another echo"
        echo "::endgroup::"
      shell: bash

    - name: Setup Ruby
      run: |
        echo "::group::Setting up ruby environment..."
        echo "testing this"
        echo "another echo"
        echo "::endgroup::"
      shell: bash

    - name: Bundle Install
      run: |
        echo "::group::Running bundle install..."
        echo "testing this"
        echo "another echo"
        echo "::endgroup::"
      shell: bash
