  
name: 'test actions'
description: 'test action description'

runs:
  using: "composite"
  steps:
  - run: printenv
    shell: bash
  - name: "run"
    env:
      WORKSPACE: ${{ github.workspace }}
    run: |
      echo $WORKSPACE
      echo ${{github.action_path}}
      echo ${{github.event_path}}
      echo ${{github.workspace}}
    shell: bash
  - name: Continue on error
    continue-on-error: true
    run: exit 1
    shell: bash
  - name: After continue on error
    run: echo "yay"
    shell: bash
