name: 'Issue'
description: 'Composite example'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '2.6.0'
runs:
  using: "composite"
  steps:
    - name: use step
      uses: nikola-jokic/failing-composite@main
      continue-on-error: true
    - name: First
      id: foo
      run: |
        exit 1
      shell: bash
      continue-on-error: true
    - name: Dump steps context
      shell: bash
      run: echo '${{ toJSON(steps) }}'

    - name: Second
      run: |
        echo 'passing'
      shell: bash

